storage: /var/lib/verdacciod/storage
auth:
  htpasswd:
    file: /var/lib/verdacciod/htpasswd
    max_users: 1000
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  "@*/*":
    access: $all
    publish: $authenticated
    proxy: npmjs
  "**":
    proxy: npmjs
listen: https://verdaccio.smanax.com
logs:
  - { type: stdout, format: pretty, level: http }
