storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  "**":
    access: $all
    publish: $authenticated
    proxy: npmjs
listen: https://verdaccio.smanax.com # if you want to use https
# - localhost:4873            # default value
# - http://localhost:4873     # same thing
# - 0.0.0.0:4873              # listen on all addresses (INADDR_ANY)
# - "[::1]:4873"                # ipv6
# - unix:/tmp/verdaccio.sock    # unix socket
logs:
  - { type: stdout, format: pretty, level: http }
